### ISSUE TITLE
Post Editor does not always display when posting via profile page.

### ISSUE THREAD

**Issue by PaulSpoerry** [PaulSpoerry/PostEditorForGooglePlus#1]
The Post Editor box and buttons do not always display when trying to use Post Editor from a profile page. Hitting F5 to refresh will make the Post Editor display.

**Comment by PaulSpoerry** [comment]
via @FiXato 

"I've been doing some console logging, and there are times where:
  console.log($('div[guidedhelpid="sharebox_editor"]'));
will return:
  [prevObject: o.fn.init[1], context: document, selector: "div[guidedhelpid="sharebox_editor"]", jquery: "2.1.0", constructor: function…]
instead of an actual DOM object. As a result, the .after() call that will insert the actual gpebuttons fails.
Not sure yet what the reason is, but I'll see if I can dig some deeper. "

**Comment by FiXato** [comment]
I just got home from an Irish night at the pub, but will probably look more into it over the weekend. :)

Hitting F5 will actually not always make it display. Most of these non-DOM-object results I've received, were actually from page refreshes.

From what I found searching for similar questions/bugs, is that this result is returned when the target isn't actually found, or when further filtering occurs that modifies the results: https://stackoverflow.com/questions/13306832/jquery-selector-returns-prevobject-instead-of-normal-element and https://stackoverflow.com/questions/19697495/what-is-prevobject-and-why-is-my-selector-returning-that

A possible solution might be to check the object type of the result, and when it doesn't return the expected object, keep polling the page till it does.

From what I have gathered so far, the longer it has been in a document.readyState='interactive' state, the more likely it is to actually find the object when it enters the document.readyState='ready' state.

A possible solution might be to attach the html insertion to a click() event on the guidedhelpid=sharebox_launcher object instead, or perhaps look into a more generic solution by attaching to something like div[role="textbox"]

**Comment by PaulSpoerry** [comment]
I pushed changes up, should now work on pages/profiles.

Yes, it appears that despite having  if (document.readyState === "complete") {  that the elements aren't fully loaded so there is nothing to attach to. It may require adding a window.addEventListener and then checking for the existence of the element needed. I'll look into that.

**Comment by PaulSpoerry** [comment]
Post editor should now poll for the existence of the element it appends to (the .after() method). If it doesn't exist it will try until it finds it. The has been tested on the stream, profile, and pages. I believe this issue is now resolved.
