### ISSUE TITLE
Post Editor clashing with Extension

### ISSUE THREAD

**Issue by Danie10** [PaulSpoerry/PostEditorForGooglePlus#10]
Post Editor was not appearing for me but I found it was clashing with another extension "Replies and more for Google+". Disabling the other extension made it work fine.

**Comment by PaulSpoerry** [comment]
@Danie10 Replies and More is no longer supported. However, I've just updated the extension and loaded Replies and More. I tested the extension with Replies and More active and it works as expected. Thanks for your patience and if you don't mind rate the extension on the Chrome store!
