### ISSUE TITLE
Italics not working Chrome 36

### ISSUE THREAD

**Issue by lisaleague** [PaulSpoerry/PostEditorForGooglePlus#12]
Italics not working in Google Chrome Version 36.0.1985.125 Mac 10.9.4

https://plus.google.com/117941735949410049434/posts/dde4bexCmw3

![lisa league google](https://cloud.githubusercontent.com/assets/3607365/3826018/ee6bb0fa-1d5b-11e4-9ccf-dc85eba03399.png)

**Comment by PaulSpoerry** [comment]
@lisaleague It's not my extension, Google+'s formatting has issues with spaces sometimes. If I copy and past just the text you want in italic into a private post is doesn't do the underline. If I remove the underscore character from both ends, trim any white space around it, and then put them back in the italic works as you'd expect. _shrug_   I've heard others have issues with spacing and the markup not working consistently before (not related to my extension). 

For that post if you edit it, remove the underscore and spacing and reapply the underscore I think it'll do what you're looking for it to do.

**Comment by lisaleague** [comment]
No worries, thought I could help out. Just fixed it, the bold worked OK.

**Comment by PaulSpoerry** [comment]
Glad you got it worked out! Congrats on your exam!

**Comment by lisaleague** [comment]
Not mine, but one of our customers, I sell the training:) thanks!

_Lisa League_
Designer, Founder Qpractice http://www.qpractice.com/
_407.385.0469_
lisa@lisaleague.com

Twitter: @agirlandamac | LinkedIn: https://www.linkedin.com/in/lisaleague
