### ISSUE TITLE
Can get Use Editor or get it to display in browser

### ISSUE THREAD

**Issue by jamesenovak** [PaulSpoerry/PostEditorForGooglePlus#13]
I really want to use PostEditorforGooglePlus. Its showing in extensions that I downloaded it. But I can't use it and can not get it to show on my tool bar.  How do I allow it, and where do I go in settings to allow? Thank-you.

**Comment by PaulSpoerry** [comment]
@jamesenovak There is no toolbar for Post Editor... as in, you won't see it display on your Chrome toolbar. When you begin to create a post on G+ at that point Post Editor will inject itself below the box that you type your post into on G+.
