### ISSUE TITLE
Post editor no longer working on Pages

### ISSUE THREAD

**Issue by PaulSpoerry** [PaulSpoerry/PostEditorForGooglePlus#14]
Post editor will work from profile and main page but has stopped working on G+ Pages.

**Comment by CoderRed99** [comment]
I can no longer see the post editor. It is still listed in my chrome extension, but does not show up when I write a comment. This has been going on for quite awhile.

**Comment by PaulSpoerry** [comment]
Is this happening on the main stream, a Page/Community, and what OS are you on @CoderRed99?

**Comment by CoderRed99** [comment]
All pages and I'm on Yosemite. I de-selected and reselected the extension
and nothing changed. After rebooting, it seems to be working in all spaces
except from Community pages. I tried multiple, both my own and others.

Warm regards,

Dianna

Extroverted Geek - ​Mobile ​Developer

**Comment by Emmadw** [comment]
I've found that it was working on one computer, but not another (see CoderRed99's comment) - though it was the same Chrome profile on both & on both showing as installed & enabled etc. I have just uninstalled & reinstalled it, on the machine that it wasn't working on - it is now. Will see on Monday if it's working on the other machine ...
