### ISSUE TITLE
Will PostEditor work with GoogleApps for Business?

### ISSUE THREAD

**Issue by singlemalt8** [PaulSpoerry/PostEditorForGooglePlus#15]
I can use the extension with my personal G+ account (thanks and great!), but it does not seem to work with G+ in my company domain.  Any ideas why?

**Comment by PaulSpoerry** [comment]
@adlermike1 Do you mean from a Google Apps for Domains login, or from a company "Page" (versus your personal stream)?

**Comment by singlemalt8** [comment]
Hmmm... I think i mean a google apps domain logon (i am in a large company
that uses google apps for business).

**Comment by PaulSpoerry** [comment]
I should have prior to the redesign. At this point the extension isn't functioning with the new G+ layout.
