### ISSUE TITLE
Add Post Editor to comments

### ISSUE THREAD

**Issue by PaulSpoerry** [PaulSpoerry/PostEditorForGooglePlus#4]
Most requested feature is to add the Post Editor to the comment box.

**Comment by kimbeasley** [comment]
I am really looking forward to having access to the Post Editor in comments. I'm so addicted to it now that I feel like I'm really missing out not having it available in comments. LOL!

**Comment by PaulSpoerry** [comment]
:)  Thanks for the feedback @kimbeasley. It's the feature people request most often; I've taken a stab at it a few times but work has been super busy and to say the G+ code is dense would be an understatement. It IS still on my radar though.

**Comment by kimbeasley** [comment]
YEAH!!! Thanks so much for creating this extension. :)

   _Kim Beasley,_
- CEO/Social Media Strategist *_Kim Beasley Consulting_
  kim@kimbeasley.com  | http://kimbeasley.com
  [image: Facebook]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/c26a6cc8d2f4a100de996dbed757a399/c99c5f3adf5d623d2ac4278b15d63b01?ytl=http%3A%2F%2Fwww.facebook.com%2FKimABeasley
  [image:
  Facebook Page]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/c26a6cc8d2f4a100de996dbed757a399/023f1d5058a3ce1c33ca0da9f8702d86?ytl=http%3A%2F%2Ffacebook.com%2FSocialMediaToolCoach
  [image:
  Twitter]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/c26a6cc8d2f4a100de996dbed757a399/b679022d73e17ce7da94913e86f95fbe?ytl=http%3A%2F%2Ftwitter.com%2Fkimbeasley
  [image:
  LinkedIn]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/c26a6cc8d2f4a100de996dbed757a399/2f55d2696e05357d1acf12d7b4b4494f?ytl=http%3A%2F%2Flinkedin.com%2Fin%2Fkbeasley%2F
  [image:
  Google Plus]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/c26a6cc8d2f4a100de996dbed757a399/f8b75ff6196b6be682a2e19e05cb08b5?ytl=https%3A%2F%2Fplus.google.com%2Fu%2F0%2F%2BKimBeasley%2Fposts
  [image:
  Google Plus Page]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/c26a6cc8d2f4a100de996dbed757a399/d6c7a3026793e0e861b54341ab60fe44?ytl=https%3A%2F%2Fplus.google.com%2Fu%2F0%2F113404037141063682408
  [image:
  pinterest]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/c26a6cc8d2f4a100de996dbed757a399/a77f425886c6d7b75997871afc4cad45?ytl=http%3A%2F%2Fpinterest.com%2Fkimabeasley
  [image:
  YouTube]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/c26a6cc8d2f4a100de996dbed757a399/f8ead354c6ad863e58ca0c5a81c62ca7?ytl=http%3A%2F%2Fwww.youtube.com%2Fuser%2FSocialMediaToolCoach
  [image: undefined]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/c26a6cc8d2f4a100de996dbed757a399/4bd42eb0f8c17e1a898af06c3a887ee1?ytl=https%3A%2F%2Fwww.facebook.com%2FSocialMediaToolCoach
