### ISSUE TITLE
creating post refreshes the entire page, then goes to URL https://plus.google.com/u/0/%23/auto

### ISSUE THREAD

**Issue by p3ngwin** [PaulSpoerry/PostEditorForGooglePlus#6]
trying to use the formatting options to E.G. bold a headline, then as soon as i press the BOLD button, the whole webpage disapears, and tries to go to this URL:

https://plus.google.com/u/0/%23/auto

**Comment by brainvision** [comment]
yea same for me! very annoying! I lost a few posts!! :(

**Comment by PaulSpoerry** [comment]
@p3ngwin & @brainvision I've just pushed up a new version if you'd like to give it a shot. I cannot replicate the page disappearing now. If it still occurs could you let me know if you have any other Google+ specific extensions installed?

**Comment by brainvision** [comment]
I just read your reply; I'll install the very last version and I'll use it for formatting the next G+ post or comment.. then I'll let you know! ;)

see ya

**Comment by PaulSpoerry** [comment]
@brainvision & @p3ngwin  I've resolved the issue where posts (specifically when posting from your page/profile... I was never able to make it error from the main stream) would redirect to https://plus.google.com/u/0/%23/auto. The latest version should get you set up and good to go. Sorry it took so long for me to get back to working on the extension!

**Comment by PaulSpoerry** [comment]
Closing the log for now but if you still have an issue let me know!!
