### ISSUE TITLE
PostEditor - Community Posts

### ISSUE THREAD

**Issue by theboffin** [PaulSpoerry/PostEditorForGooglePlus#9]
PostEditor does not appear to be activated when posting on a community

![20-03-2014 09-04-53](https://f.cloud.github.com/assets/631978/2470222/b6fb7ef8-b00e-11e3-8448-184eb2f81f02.jpg)

**Comment by brainvision** [comment]
it works for me..

![posteditor g](https://f.cloud.github.com/assets/229026/2475606/4dcce07a-b059-11e3-884f-9fc6f6a3fb31.PNG)

**Comment by PaulSpoerry** [comment]
@theboffin Make sure you let the page fully load. Google+ does a LOT of code injection during and after the page has loaded. I think that might be tripping it up (and I'm looking into that and how I might circumvent it). Report back if waiting a bit before using the share box helps.

**Comment by PaulSpoerry** [comment]
@brainvision Thanks for confirming it worked for you.

@theboffin I've pushed up a new version that should be more reliable in injecting the code. I'm going to close this issue but if you still have issues please report back. If it's now working for you I'd really appreciate you giving it some positive feedback on the Chrome store: https://chrome.google.com/webstore/detail/post-editor-for-google%2B/canbakmdapinjpiabkbdgmpenllifmij
